// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shaos.Repository;

#nullable disable

namespace Shaos.Repository.Migrations
{
    [DbContext(typeof(ShaosDbContext))]
    [Migration("20250705201542_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("Shaos.Repository.Models.Devices.BaseParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParameterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("BaseParameter");

                    b.HasDiscriminator().HasValue("BaseParameter");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SignalLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugInInstanceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Shaos.Repository.Models.LogLevelSwitch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LogLevelSwitches");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlugIns");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PlugInId");

                    b.ToTable("PlugInInstances");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.BooleanParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.BaseParameter");

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BooleanParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.FloatParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.BaseParameter");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("FloatParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("FloatParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.IntParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.BaseParameter");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("IntParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("IntParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.StringParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.BaseParameter");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("StringParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("StringParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.UIntParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.BaseParameter");

                    b.Property<uint>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("UIntParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("UIntParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.BaseParameter", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Device", "Device")
                        .WithMany("Parameters")
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Device", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugInInstance", "PlugInInstance")
                        .WithMany("Devices")
                        .HasForeignKey("PlugInInstanceId");

                    b.Navigation("PlugInInstance");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.OwnsOne("Shaos.Repository.Models.Package", "Package", b1 =>
                        {
                            b1.Property<int>("PlugInId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AssemblyFile")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AssemblyVersion")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasConfiguration")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasLogger")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlugInId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PlugInId");
                        });

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithMany("Instances")
                        .HasForeignKey("PlugInId");

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Device", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
