// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shaos.Repository;

#nullable disable

namespace Shaos.Repository.Migrations
{
    [DbContext(typeof(ShaosDbContext))]
    [Migration("20250406161511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Shaos.Repository.Models.LogLevelSwitch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_LogLevelSwitch");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_LogLevelSwitch_Name_Ascending");

                    b.ToTable("LogLevelSwitches");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyFile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_PackageId");

                    b.HasIndex("PlugInId")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_PlugInId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PlugIn_Name_Ascending");

                    b.ToTable("PlugIns");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_PlugInInstanceId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PlugInInstance_Name_Ascending");

                    b.HasIndex("PlugInId");

                    b.ToTable("PlugInInstances");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Package", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithOne("Package")
                        .HasForeignKey("Shaos.Repository.Models.Package", "PlugInId");

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithMany("Instances")
                        .HasForeignKey("PlugInId");

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Package");
                });
#pragma warning restore 612, 618
        }
    }
}
