// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shaos.Repository;

#nullable disable

namespace Shaos.Repository.Migrations
{
    [DbContext(typeof(ShaosDbContext))]
    [Migration("20260206174131_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Features")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SignalLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugInInstanceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BaseParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParameterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("BaseParameter");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseParameter");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BaseParameterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseParameterValue");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseParameterValue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shaos.Repository.Models.LogLevelSwitch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LogLevelSwitches");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlugIns");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyFileName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasConfiguration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLogger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageFileName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugInId")
                        .IsUnique();

                    b.ToTable("PlugInInformations");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PlugInId");

                    b.ToTable("PlugInInstances");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BoolParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameter");

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BoolParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.FloatParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameter");

                    b.Property<float>("Max")
                        .HasColumnType("REAL");

                    b.Property<float>("Min")
                        .HasColumnType("REAL");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("FloatParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("FloatParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.IntParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameter");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Max")
                                .HasColumnName("IntParameter_Max");

                            t.Property("Min")
                                .HasColumnName("IntParameter_Min");

                            t.Property("Value")
                                .HasColumnName("IntParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("IntParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.StringParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameter");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("StringParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("StringParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.UIntParameter", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameter");

                    b.Property<uint>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("BaseParameter", t =>
                        {
                            t.Property("Max")
                                .HasColumnName("UIntParameter_Max");

                            t.Property("Min")
                                .HasColumnName("UIntParameter_Min");

                            t.Property("Value")
                                .HasColumnName("UIntParameter_Value");
                        });

                    b.HasDiscriminator().HasValue("UIntParameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BoolParameterValue", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameterValue");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ParameterId");

                    b.HasDiscriminator().HasValue("BoolParameterValue");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.FloatParameterValue", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameterValue");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasIndex("ParameterId");

                    b.ToTable("BaseParameterValue", t =>
                        {
                            t.Property("ParameterId")
                                .HasColumnName("FloatParameterValue_ParameterId");

                            t.Property("Value")
                                .HasColumnName("FloatParameterValue_Value");
                        });

                    b.HasDiscriminator().HasValue("FloatParameterValue");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.IntParameterValue", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameterValue");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ParameterId");

                    b.ToTable("BaseParameterValue", t =>
                        {
                            t.Property("ParameterId")
                                .HasColumnName("IntParameterValue_ParameterId");

                            t.Property("Value")
                                .HasColumnName("IntParameterValue_Value");
                        });

                    b.HasDiscriminator().HasValue("IntParameterValue");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.StringParameterValue", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameterValue");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasIndex("ParameterId");

                    b.ToTable("BaseParameterValue", t =>
                        {
                            t.Property("ParameterId")
                                .HasColumnName("StringParameterValue_ParameterId");

                            t.Property("Value")
                                .HasColumnName("StringParameterValue_Value");
                        });

                    b.HasDiscriminator().HasValue("StringParameterValue");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.UIntParameterValue", b =>
                {
                    b.HasBaseType("Shaos.Repository.Models.Devices.Parameters.BaseParameterValue");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Value")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ParameterId");

                    b.ToTable("BaseParameterValue", t =>
                        {
                            t.Property("ParameterId")
                                .HasColumnName("UIntParameterValue_ParameterId");

                            t.Property("Value")
                                .HasColumnName("UIntParameterValue_Value");
                        });

                    b.HasDiscriminator().HasValue("UIntParameterValue");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Device", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugInInstance", "PlugInInstance")
                        .WithMany("Devices")
                        .HasForeignKey("PlugInInstanceId");

                    b.Navigation("PlugInInstance");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BaseParameter", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Device", "Device")
                        .WithMany("Parameters")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInformation", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithOne("PlugInInformation")
                        .HasForeignKey("Shaos.Repository.Models.PlugInInformation", "PlugInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithMany("Instances")
                        .HasForeignKey("PlugInId");

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BoolParameterValue", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Parameters.BoolParameter", "Parameter")
                        .WithMany("Values")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.FloatParameterValue", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Parameters.FloatParameter", "Parameter")
                        .WithMany("Values")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.IntParameterValue", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Parameters.IntParameter", "Parameter")
                        .WithMany("Values")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.StringParameterValue", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Parameters.StringParameter", "Parameter")
                        .WithMany("Values")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.UIntParameterValue", b =>
                {
                    b.HasOne("Shaos.Repository.Models.Devices.Parameters.UIntParameter", "Parameter")
                        .WithMany("Values")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Device", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("PlugInInformation");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.BoolParameter", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.FloatParameter", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.IntParameter", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.StringParameter", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shaos.Repository.Models.Devices.Parameters.UIntParameter", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
