// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shaos.Repository;

#nullable disable

namespace Shaos.Repository.Migrations
{
    [DbContext(typeof(ShaosDbContext))]
    partial class ShaosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Shaos.Repository.Models.LogLevelSwitch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_LogLevelSwitch");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_LogLevelSwitch_Name_Ascending");

                    b.ToTable("LogLevelSwitches");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_PlugInId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PlugIn_Name_Ascending");

                    b.ToTable("PlugIns");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_PlugInInstanceId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PlugInInstance_Name_Ascending");

                    b.HasIndex("PlugInId");

                    b.ToTable("PlugInInstances");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.OwnsOne("Shaos.Repository.Models.Package", "Package", b1 =>
                        {
                            b1.Property<int>("PlugInId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AssemblyFile")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.HasKey("PlugInId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PlugInId");
                        });

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugInInstance", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithMany("Instances")
                        .HasForeignKey("PlugInId");

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
