// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shaos.Repository;

#nullable disable

namespace Shaos.Repository.Migrations
{
    [DbContext(typeof(ShaosDbContext))]
    partial class ShaosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Shaos.Repository.Models.CodeFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugInId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugInId");

                    b.ToTable("CodeFiles");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Name_Ascending");

                    b.ToTable("PlugIns");
                });

            modelBuilder.Entity("Shaos.Repository.Models.CodeFile", b =>
                {
                    b.HasOne("Shaos.Repository.Models.PlugIn", "PlugIn")
                        .WithMany("CodeFiles")
                        .HasForeignKey("PlugInId");

                    b.Navigation("PlugIn");
                });

            modelBuilder.Entity("Shaos.Repository.Models.PlugIn", b =>
                {
                    b.Navigation("CodeFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
