# Update configuration to match application configuration
@accesstoken = "SET THIS TO BEARER TOKEN"
@address = https://localhost:7000
@email = me@here.com
@password = j+8KPrmgMiWi^+N
@version = 1

###

# This will generate a bearer token and refresh token
# Used to generate access token for API access

POST {{address}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

GET {{address}}/api/v{{version}}/system/environment
Authorization: Bearer {{accesstoken}}
Accept: application/json

###