# Update configuration to match application configuration
@HostAddress = https://localhost:7000
@email = me@here.com
@badPassword = password
@password = j+8KPrmgMiWi^+N

###

GET {{HostAddress}}/api/System
Accept: application/json

###

POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###