# Update configuration to match application configuration
@address = https://localhost:7000
@email = me@here.com
@password = j+8KPrmgMiWi^+N

###

# This will generate a bearer token and refresh token
# Used to generate access token for API access

POST {{address}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
