# Update configuration to match application configuration
@accesstoken = "SET THIS TO BEARER TOKEN"
@address = https://localhost:7000
@version = 1

GET {{address}}/api/v{{version}}/app-events
Authorization: Bearer {{accesstoken}}
Accept: text/event-stream

###

GET {{address}}/api/v{{version}}/log-events
Authorization: Bearer {{accesstoken}}
Accept: text/event-stream

###

GET {{address}}/api/v{{version}}/parameter-events
Authorization: Bearer {{accesstoken}}
Accept: text/event-stream