# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
@accesstoken = "SET THIS TO BEARER TOKEN"
@address = https://localhost:7000
@id = 1
@name = System
@level = Verbose
@version = 1

###

# Get the logging level
GET {{address}}/api/v{{version}}/logging/levels
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Get the logging level
GET {{address}}/api/v{{version}}/logging/levels?name={{name}}&level={{level}}
Authorization: Bearer {{accesstoken}}
Accept: application/json

###
