# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
# Set the token to value returned from auth
@address = https://localhost:7000
@version = 1
@token = TOKEN
@name = System
@level = Verbose

###

# Get the logging level
GET {{address}}/api/v{{version}}/logging/levels
Authorization: Bearer {{token}}
Accept: application/json

###
