# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
# Set the token to value returned from auth
@address = https://localhost:7000
@version = 1
@token = TOKEN

@parameterid = 1

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/bool/true
Authorization: Bearer {{token}}
Accept: application/json

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/float/1.2
Authorization: Bearer {{token}}
Accept: application/json

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/int/-10
Authorization: Bearer {{token}}
Accept: application/json

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/uint/34
Authorization: Bearer {{token}}
Accept: application/json