# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
# Set the token to value returned from auth
@address = https://localhost:7000
@version = 1
@token = CfDJ8IQaOmo7hBxKqaUm9FjzvNdcyC_UvIXKj7Opw4ksg47R1Tjlgi5XWgmW0DER2YwbrURzuOtwyf61RlOSA5_jXjYIatzL9Kdly2YJ7MiT6t1tFK4iE47Ry25SCsPHbv_egPAN9jQ43l0W5Rl7UXVSXHB8KOsJaV8lmZLx3Nbcs3K8S4tuexRG2cOaogS1fOf85t5tHg7OLBKcH7qPUiag_MGnbt1702vjYufUlfhkdznyPRP9uz86kdPhslqDkE6ruOmG9xYRFJzbXGY2WzMV9WNqdHFGscMGJ6UBBLW9FoQ3XakWS9CvnAIUp7X4V8Ggvs8nNPoYWvbD7xRZLBB2fWe6sk-rVm6hQZZsNxcWxlEZI5ceurhS-gqueH3OzOejc8ehuSXw7AJ3_WI1ViMns6cXuwhB2ohL3vCp2OcGtnakqRxmW9J7jSMqzvUxVOT3Ge6m6ZwCZRaJ4XYmumucRnkpNYnKahbQ2dPjXPyjKyiX2YFqh75k0ccd5DgJJ0GBMwFrwlbs9aLlv2wzMiqF-Iu5SekiP0y8lOqY-ZryqpE6fRVIYXGKpDdnNobc4-avip5_gx_a63ZF9-MkFqie_uJoUMmF_T5YK33Y98Q39yQH9G48YfRlqjrm2bPyeHe6ynt9r3M9IG5j9PczfEdNI5h0F1UkGrHeF0X649DYn8agetVh8X3XIL5MyF9iXgioaw

@parameterid = 1

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/bool/true
Authorization: Bearer {{token}}
Accept: application/json

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/float/1.2
Authorization: Bearer {{token}}
Accept: application/json

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/int/-10
Authorization: Bearer {{token}}
Accept: application/json

###

# Write a boolean value to a parameter
PUT {{address}}/api/v{{version}}/parameters/{{parameterid}}/uint/34
Authorization: Bearer {{token}}
Accept: application/json