# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
# Set the token to value returned from auth
@address = https://localhost:7000
@version = 1
@token = TOKEN

@id = 1

###

# Get the list of runtime plugin instances
GET {{address}}/api/v{{version}}/runtime
Authorization: Bearer {{token}}
Accept: application/json

###

# Start an instance executing
PUT {{address}}/api/v{{version}}/runtime/{{id}}/start
Authorization: Bearer {{token}}
Accept: application/json

###

# Stop an instance executing
PUT {{address}}/api/v{{version}}/runtime/{{id}}/stop
Authorization: Bearer {{token}}
Accept: application/json

###