# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
@accesstoken = "SET THIS TO BEARER TOKEN"
@address = https://localhost:7000
@id = 1
@version = 1

###

# Get executing instances
GET {{address}}/api/v{{version}}/runtime
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Get all executing instances
GET {{address}}/api/v{{version}}/runtime
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Start an instance executing
PUT {{address}}/api/v{{version}}/runtime/{{id}}/start
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Stop an instance executing
PUT {{address}}/api/v{{version}}/runtime/{{id}}/stop
Authorization: Bearer {{accesstoken}}
Accept: application/json

###