# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
# Set the token to value returned from auth
@address = https://localhost:7000
@version = 1
@token = TOKEN
@id = 1

###

# Get the system environment information
GET {{address}}/api/v{{version}}/system/environment
Authorization: Bearer {{token}}
Accept: application/json

###

# Get the system os version
GET {{address}}/api/v{{version}}/system/os
Authorization: Bearer {{token}}
Accept: application/json

###

# Get the system process information
GET {{address}}/api/v{{version}}/system/process
Authorization: Bearer {{token}}
Accept: application/json

###

# Get the system process information
GET {{address}}/api/v{{version}}/system/version
Authorization: Bearer {{token}}
Accept: application/json

###

# Shutdown the system
POST {{address}}/api/v1/system/shutdown
Authorization: Bearer {{token}}
Accept: application/json
