# Update configuration to match application configuration
# Use the Autorisation.http script to generate an access token
@accesstoken = "SET THIS TO BEARER TOKEN"
@address = https://localhost:7000
@version = 1

###

# Get the system version
GET {{address}}/api/v{{version}}/system/version
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Shutdown the system
POST {{address}}/api/v{{version}}/system/shutdown
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Get the operating system information
GET {{address}}/api/v{{version}}/system/os
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Get the application environment information
GET {{address}}/api/v{{version}}/system/environment
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

# Get the application process information
GET {{address}}/api/v{{version}}/system/process
Authorization: Bearer {{accesstoken}}
Accept: application/json

###

